### ISSUE TITLE
Uncaught TypeError: Class constructor App cannot be invoked without 'new'     at new WDYUClassComponent

### ISSUE THREAD

**Issue by zengguangzhong** [maicki/why-did-you-update#56]
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";

const { whyDidYouUpdate } = require("why-did-you-update");
whyDidYouUpdate(React);

ReactDOM.render(<App />, document.getElementById("root"));

// react  "version": "16.8.6"

**Comment by vzaidman** [comment]
fixed in https://github.com/welldone-software/why-did-you-render/issues/5 in the `@welldone-software/why-did-you-render` project:
https://github.com/welldone-software/why-did-you-render

you are free to open a PR on this library to fix it.

also, you can use the `@babel/plugin-transform-classes` plugin in your project. for example:
```
      ['@babel/preset-env', {
        ..... // your other settings
        include: [
          // remove when `https://github.com/babel/babel/issues/7022` is solved
          '@babel/plugin-transform-classes'
        ]
      }],
```

**Comment by maicki** [comment]
Closing this Issue. For further details please look at: #63
